apiVersion: v1
kind: Pod
metadata:
  name: tf-latest
spec:
  containers:
  - name: tf-latest
    image: tensorflow/tensorflow:latest-devel-gpu-py3
    imagePullPolicy: IfNotPresent
    command: ['/bin/sh']
    args: ['-c', 'pwd']
    env:
        - name: COMET_API_KEY
        valueFrom:
            secretKeyRef:
                name: logger
                key: logapi
    resources:
      limits:
        nvidia.com/gpu: 1
    volumes:
    - name: git-volume
        gitRepo:
            repository: ''
