apiVersion: v1
kind: Pod
metadata:
  name: tf-latest
spec:
  restartPolicy: Never
  containers:
  - name: tf-latest
    image: ryanhausen/ryanml:latest
    imagePullPolicy: IfNotPresent
    command: ['/bin/sh', '-c']
    args: ['python reduced_dataset_tf.py']
    #args: ['pwd']
    env:
    - name: COMET_API_KEY
      valueFrom:
        secretKeyRef:
          name: logger
          key: logapi
    resources:
      limits:
        nvidia.com/gpu: 1
        memory: 16Gi
    volumeMounts:
    - name: gitrepo
      mountPath: /root/src


# https://gist.github.com/tallclair/849601a16cebeee581ef2be50c351841
  initContainers:
  - name: git-setup
    image: alpine/git
    command: ['/bin/sh', '-c']
    args: ['git clone https://github.com/ryanhausen/nautilus-cifar10.git /repo && mv /transit/* /repo/']
    volumeMounts:
    - name: gitrepo
      mountPath: /repo
    - name: transit
      mountPath: /transit
  volumes:
  - name: gitrepo
    emptyDir: {}
  - name: transit
    persistentVolumeClaim:
      claimName: transit
