apiVersion: v1
kind: Pod
metadata:
  name: tf-latest
spec:
  containers:
  - name: tf-latest
    image: ryanhausen/ryanml:latest
    imagePullPolicy: IfNotPresent
    command: ['/bin/sh', '-c']
    args: ['python /workspace/reduced_dataset_training.py']
    env:
    - name: COMET_API_KEY
      valueFrom:
        secretKeyRef:
          name: logger
          key: logapi
    resources:
      limits:
        nvidia.com/gpu: 1
    volumeMounts:
    - name: workspace
      mountPath: /workspace

  initContainers:
  - name: git-setup
    image: gitlab/gitlab-ce
    command: ['/bin/sh', '-c']
    args: ['git clone https://github.com/ryanhausen/nautilus-cifar10.git /workspace']
    volumeMounts:
    - name: workspace
      mountPath: /workspace
  volumes:
  - name: workspace
    emptyDir: {}

