apiVersion: v1
kind: Pod
metadata:
  name: tf-latest
spec:
  containers:
  - name: tf-latest
    image: tensorflow/tensorflow:latest-devel-gpu-py3
    imagePullPolicy: IfNotPresent
    command: ['/bin/sh']
    args: ['-c', 'pwd']
    resources:
      limits:
        nvidia.com/gpu: 1
